#Build testing for LICHEM

#NB: Currently the OSX build skips the documentation

#Email settings
# notifications:
#   email:
#     on_success: change
#     on_failure: always

#Compiler settings
language: cpp
compiler:
  - gcc
  - clang

#OS settings
sudo: required
dist: xenial
os:
  - linux
  - osx

#Install required packages
before_install:
  ### Linux options
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo apt-get install -qq texlive; fi
  ## Find the missing library (Travis Ubuntu -L issue). Need -qq for all installs
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo apt-get install -qq libomp-dev; fi
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo apt-get install -qq libiomp5; fi
  ## Remove space if Makefile has "CXX=g++" !
  - if [ ${TRAVIS_OS_NAME} == linux ]; then if [ ${CXX} == clang++ ]; then sed -i 's/CXX= /CXX=clan/g' Makefile; fi; fi
  - if [ ${TRAVIS_OS_NAME} == linux ]; then if [ ${CC} == clang ]; then sed -i 's/CC=/CC=clan/g' Makefile; fi; fi
  # Change flag for Linux C++
  - if [ ${TRAVIS_OS_NAME} == linux ]; then if [ ${CXX} == clang++ ]; then sed -i 's/CXXFLAGS=/CXXFLAGS= -static -O3 -fopenmp=libomp -std=c+11/g' Makefile; fi; fi
  - if [ ${TRAVIS_OS_NAME} == linux ]; then if [ ${CC} == clang ]; then sed -i 's/CXXFLAGS=/CXXFLAGS= -static -O3 -fopenmp=libomp -std=c+11/g' Makefile; fi; fi
  #
  #- if [ ${TRAVIS_OS_NAME} == linux ]; then if [ ${CC} == clang ] || [ ${CXX} == clang++ ]; then sed -i 's/-fopenmp/-fopenmp=libomp/g' Makefile; fi; fi
  ### OSX options
  - if [ ${TRAVIS_OS_NAME} == osx ]; then brew update; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then if [ ${CXX} == clang++ ]; then sed -i "" 's/CXX= /CXX=clan/g' Makefile; fi; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then if [ ${CC} == clang ]; then sed -i "" 's/CC=/CC=clan/g' Makefile; fi; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" 's/-static//g' Makefile; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" 's/-fopenmp//g' Makefile; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" 's/SEDI=-i/SEDI=-i \"\"/g' Makefile; fi

script:
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo ldconfig; fi
  - make install && make clean
  - if [ ${TRAVIS_OS_NAME} == linux ]; then apt-get moo; fi
