#Build testing for LICHEM

#NB: Currently the OSX build skips the documentation

#Email settings
# notifications:
#   email:
#     on_success: change
#     on_failure: always

#Compiler settings
language: cpp

matrix:
    include:

    # GCC Linux: works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - texlive
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # Clang Linux: works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - texlive
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"

    ## OSX GCC
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

    ## OSX clang
    - os: osx
      osx_image: xcode9.4

#Install required packages
before_install:
  - eval "${MATRIX_EVAL}"
  ## Remove space if Makefile has "CXX=g++" !
  - if [ ${TRAVIS_OS_NAME} == linux ]; then if [ ${CXX} == clang++ ]; then sed -i 's/CXX= /CXX=clan/g' Makefile; fi; fi
  - if [ ${TRAVIS_OS_NAME} == linux ]; then if [ ${CC} == clang ]; then sed -i 's/CC=/CC=clan/g' Makefile; fi; fi
  - if [ ${TRAVIS_OS_NAME} == linux ]; then if [ ${CC} == clang ] || [ ${CXX} == clang++ ]; then sed -i 's/-fopenmp/-I\/usr\/include -fopenmp/g' Makefile; fi; fi
  ### OSX options
  - if [ ${TRAVIS_OS_NAME} == osx ]; then brew update; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then if [ ${CXX} == clang++ ]; then sed -i "" 's/CXX= /CXX=clan/g' Makefile; fi; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then if [ ${CC} == clang ]; then sed -i "" 's/CC=/CC=clan/g' Makefile; fi; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" 's/-static//g' Makefile; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" 's/-fopenmp//g' Makefile; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" 's/SEDI=-i/SEDI=-i \"\"/g' Makefile; fi

script:
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo ldconfig; fi
  - make install && make clean
  - if [ ${TRAVIS_OS_NAME} == linux ]; then apt-get moo; fi
