#Build testing for LICHEM

#NB: Currently the OSX build skips the documentation

#Email settings
# notifications:
#   email:
#     on_success: change
#     on_failure: always

#Compiler settings
language: cpp
compiler:
  - gcc
  - clang

#OS settings
sudo: required
dist: trusty
os:
  - linux
  - osx

#Install required packages
before_install:
  ### Linux options
  - if [ ${TRAVIS_OS_NAME} == linux ]; then sudo apt-get install -qq texlive; fi
  ## Remove space if Makefile has "CXX=g++" !
  - if [ ${TRAVIS_OS_NAME} == linux ]; then if [ ${CXX} == clang++ ]; then sed -i 's/CXX= /CXX=clan/g' Makefile; fi; fi
  - if [ ${TRAVIS_OS_NAME} == linux ]; then if [ ${CC} == clang ]; then sed -i 's/CC=/CC=clan/g' Makefile; fi; fi
  ## Symlink the missing clang library
  - if [ ${TRAVIS_OS_NAME} == linux ]; then if [ ${CXX} == clang++ ] || [ ${CC} == clang ]; then sudo ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so.1 /usr/lib/libOpenCL.so; fi; fi
  ### OSX options
  - if [ ${TRAVIS_OS_NAME} == osx ]; then brew update; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then if [ ${CXX} == clang++ ]; then sed -i "" 's/CXX= /CXX=clan/g' Makefile; fi; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then if [ ${CC} == clang ]; then sed -i "" 's/CC=/CC=clan/g' Makefile; fi; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" 's/-static//g' Makefile; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" 's/-fopenmp//g' Makefile; fi
  - if [ ${TRAVIS_OS_NAME} == osx ]; then sed -i "" 's/SEDI=-i/SEDI=-i \"\"/g' Makefile; fi

script:
  - make install && make clean
  - if [ ${TRAVIS_OS_NAME} == linux ]; then apt-get moo; fi
